
using Pack3r.Logging;
using Pack3r.Parsers;

namespace Pack3r.Tests;

public static class AseParserTests
{
    [Fact]
    public static async Task Should_Parse()
    {
        var reader = new StringLineReader(Data);
        var parser = new AseParser(NullLogger<AseParser>.Instance, reader);

        Assert.True(parser.CanParse("model.ase".AsMemory()));
        Assert.False(parser.CanParse("model.obj".AsMemory()));

        var result = await parser.Parse(new MockAsset(), default);

        Assert.NotNull(result);
        Assert.Equal(
        [
            "textures/venice_ase_c1/box_m02",
            "textures/venice_ase_c1/box_m03",
            "textures/venice_ase_c1/box_m01",
        ], result.Select(s => s.Value.ToString()));
    }

    private const string Data =
    """
    *3DSMAX_ASCIIEXPORT	200
*COMMENT	"Generated by Q3Map2 (ydnar) -convert -format ase"
*SCENE	{
	*SCENE_FILENAME	"box_m02.bsp"
	*SCENE_FIRSTFRAME	0
	*SCENE_LASTFRAME	100
	*SCENE_FRAMESPEED	30
	*SCENE_TICKSPERFRAME	160
	*SCENE_BACKGROUND_STATIC	0.0000	0.0000	0.0000
	*SCENE_AMBIENT_STATIC	0.0000	0.0000	0.0000
}
*MATERIAL_LIST	{
	*MATERIAL_COUNT	3
	*MATERIAL	0	{
		*MATERIAL_NAME	"textures/venice_ase_c1/box_m02"
		*MATERIAL_CLASS	"Standard"
		*MATERIAL_DIFFUSE	1.000000	0.880850	0.571197
		*MATERIAL_SHADING Phong
		*MAP_DIFFUSE	{
			*MAP_NAME	"textures/venice_ase_c1/box_m02"
			*MAP_CLASS	"Bitmap"
			*MAP_SUBNO	1
			*MAP_AMOUNT	1.0
			*MAP_TYPE	Screen
			*BITMAP	"textures/venice_ase_c1/box_m02"
			*BITMAP_FILTER	Pyramidal
		}
	}
	*MATERIAL	1	{
		*MATERIAL_NAME	"textures/venice_ase_c1/box_m03"
		*MATERIAL_CLASS	"Standard"
		*MATERIAL_DIFFUSE	1.000000	0.886761	0.619810
		*MATERIAL_SHADING Phong
		*MAP_DIFFUSE	{
			*MAP_NAME	"textures/venice_ase_c1/box_m03"
			*MAP_CLASS	"Bitmap"
			*MAP_SUBNO	1
			*MAP_AMOUNT	1.0
			*MAP_TYPE	Screen
			*BITMAP	"textures/venice_ase_c1/box_m03"
			*BITMAP_FILTER	Pyramidal
		}
	}
	*MATERIAL	2	{
		*MATERIAL_NAME	"textures/venice_ase_c1/box_m01"
		*MATERIAL_CLASS	"Standard"
		*MATERIAL_DIFFUSE	1.000000	0.887614	0.607439
		*MATERIAL_SHADING Phong
		*MAP_DIFFUSE	{
			*MAP_NAME	"textures/venice_ase_c1/box_m01"
			*MAP_CLASS	"Bitmap"
			*MAP_SUBNO	1
			*MAP_AMOUNT	1.0
			*MAP_TYPE	Screen
			*BITMAP	"textures/venice_ase_c1/box_m01"
			*BITMAP_FILTER	Pyramidal
		}
	}
}
*GEOMOBJECT	{
	*NODE_NAME	"mat2model0surf0"
	*NODE_TM	{
		*NODE_NAME	"mat2model0surf0"
		*INHERIT_POS	0	0	0
		*INHERIT_ROT	0	0	0
		*INHERIT_SCL	0	0	0
		*TM_ROW0	1.0	0	0
		*TM_ROW1	0	1.0	0
		*TM_ROW2	0	0	1.0
		*TM_ROW3	0	0	0
		*TM_POS	0.000000	0.000000	0.000000
	}
}
""";   
}
